build:monitor.cpp scheduler.cpp timer.c while1.c
	g++ -std=c++11 -O3 -o scheduler scheduler.cpp
	g++ -std=c++11 -O3 -o monitor monitor.cpp
	gcc -Wall -o while1 while1.c
	gcc -Wall -o timer timer.c

clean:
	rm -f monitor
